-- Day Assistant MVP Implementation
-- Manages NOW/NEXT/LATER task queue, energy modes, and user preferences

-- Energy mode type
CREATE TYPE energy_mode AS ENUM ('crisis', 'normal', 'flow');

-- Task priority for day assistant
CREATE TYPE day_priority AS ENUM ('now', 'next', 'later');

-- Task action type
CREATE TYPE task_action_type AS ENUM ('pin_today', 'not_today', 'mega_important', 'move_to_now', 'move_to_next', 'move_to_later');

-- Day Assistant Tasks (extends Todoist tasks with day planning metadata)
CREATE TABLE IF NOT EXISTS day_assistant_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  todoist_task_id TEXT,  -- reference to Todoist task if synced
  title TEXT NOT NULL,
  description TEXT,
  priority day_priority DEFAULT 'later',
  is_pinned BOOLEAN DEFAULT FALSE,
  is_mega_important BOOLEAN DEFAULT FALSE,
  energy_mode_required energy_mode DEFAULT 'normal',
  estimated_duration INTEGER DEFAULT 15,  -- in minutes
  due_date DATE,
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP,
  position INTEGER DEFAULT 0,  -- for ordering within priority group
  metadata JSONB DEFAULT '{}',  -- additional task metadata
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Subtasks (generated by AI)
CREATE TABLE IF NOT EXISTS day_assistant_subtasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID REFERENCES day_assistant_tasks(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  estimated_duration INTEGER DEFAULT 5,  -- in minutes
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- User Energy Mode State (current state for the user)
CREATE TABLE IF NOT EXISTS user_energy_state (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id),
  current_mode energy_mode DEFAULT 'normal',
  last_changed TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Subtask Feedback (for AI learning)
CREATE TABLE IF NOT EXISTS subtask_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  subtask_id UUID REFERENCES day_assistant_subtasks(id) ON DELETE CASCADE,
  task_id UUID REFERENCES day_assistant_tasks(id) ON DELETE CASCADE,
  feedback_type TEXT CHECK (feedback_type IN ('ok', 'too_small', 'too_big', 'nonsense', 'simplify', 'split_more')),
  feedback_stage TEXT CHECK (feedback_stage IN ('pre_completion', 'post_completion')),
  detail_level TEXT CHECK (detail_level IN ('minimum', 'standard', 'detailed')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Task Action History (for undo and tracking)
CREATE TABLE IF NOT EXISTS task_action_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  task_id UUID REFERENCES day_assistant_tasks(id) ON DELETE CASCADE NOT NULL,
  action_type task_action_type NOT NULL,
  previous_state JSONB,  -- snapshot before action
  new_state JSONB,       -- snapshot after action
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

-- User Preferences for AI subtask generation
CREATE TABLE IF NOT EXISTS user_day_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id),
  default_detail_level TEXT CHECK (default_detail_level IN ('minimum', 'standard', 'detailed')) DEFAULT 'standard',
  preferred_step_duration INTEGER DEFAULT 15,  -- in minutes
  preferences JSONB DEFAULT '{}',  -- learned preferences from feedback
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Flow Blocks (optional feature for Phase 10)
CREATE TABLE IF NOT EXISTS flow_blocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  title TEXT NOT NULL,
  context_type TEXT,  -- e.g., 'emails', 'calls', 'writing'
  estimated_duration INTEGER DEFAULT 45,  -- total block duration in minutes
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  interrupted BOOLEAN DEFAULT FALSE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

-- Flow Block Tasks (tasks within a flow block)
CREATE TABLE IF NOT EXISTS flow_block_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  block_id UUID REFERENCES flow_blocks(id) ON DELETE CASCADE NOT NULL,
  task_id UUID REFERENCES day_assistant_tasks(id) ON DELETE CASCADE NOT NULL,
  position INTEGER DEFAULT 0,
  completed BOOLEAN DEFAULT FALSE,
  skipped BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_day_tasks_user_id ON day_assistant_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_day_tasks_priority ON day_assistant_tasks(priority);
CREATE INDEX IF NOT EXISTS idx_day_tasks_completed ON day_assistant_tasks(completed);
CREATE INDEX IF NOT EXISTS idx_day_tasks_position ON day_assistant_tasks(position);
CREATE INDEX IF NOT EXISTS idx_day_subtasks_task_id ON day_assistant_subtasks(task_id);
CREATE INDEX IF NOT EXISTS idx_task_history_user_id ON task_action_history(user_id);
CREATE INDEX IF NOT EXISTS idx_task_history_created_at ON task_action_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subtask_feedback_user_id ON subtask_feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_flow_blocks_user_id ON flow_blocks(user_id);

-- Row Level Security (RLS)
ALTER TABLE day_assistant_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE day_assistant_subtasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_energy_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE subtask_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_action_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_day_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_block_tasks ENABLE ROW LEVEL SECURITY;

-- RLS Policies for day_assistant_tasks
CREATE POLICY "Users can view their own tasks"
  ON day_assistant_tasks FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own tasks"
  ON day_assistant_tasks FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tasks"
  ON day_assistant_tasks FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tasks"
  ON day_assistant_tasks FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for day_assistant_subtasks
CREATE POLICY "Users can view subtasks of their tasks"
  ON day_assistant_subtasks FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM day_assistant_tasks
    WHERE id = day_assistant_subtasks.task_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can create subtasks for their tasks"
  ON day_assistant_subtasks FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM day_assistant_tasks
    WHERE id = day_assistant_subtasks.task_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can update subtasks of their tasks"
  ON day_assistant_subtasks FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM day_assistant_tasks
    WHERE id = day_assistant_subtasks.task_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can delete subtasks of their tasks"
  ON day_assistant_subtasks FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM day_assistant_tasks
    WHERE id = day_assistant_subtasks.task_id
    AND user_id = auth.uid()
  ));

-- RLS Policies for user_energy_state
CREATE POLICY "Users can view their own energy state"
  ON user_energy_state FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own energy state"
  ON user_energy_state FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own energy state"
  ON user_energy_state FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policies for subtask_feedback
CREATE POLICY "Users can view their own feedback"
  ON subtask_feedback FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own feedback"
  ON subtask_feedback FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for task_action_history
CREATE POLICY "Users can view their own action history"
  ON task_action_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own action history"
  ON task_action_history FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for user_day_preferences
CREATE POLICY "Users can view their own preferences"
  ON user_day_preferences FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own preferences"
  ON user_day_preferences FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own preferences"
  ON user_day_preferences FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policies for flow_blocks
CREATE POLICY "Users can view their own flow blocks"
  ON flow_blocks FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own flow blocks"
  ON flow_blocks FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own flow blocks"
  ON flow_blocks FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own flow blocks"
  ON flow_blocks FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for flow_block_tasks
CREATE POLICY "Users can view tasks in their flow blocks"
  ON flow_block_tasks FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM flow_blocks
    WHERE id = flow_block_tasks.block_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can create tasks in their flow blocks"
  ON flow_block_tasks FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM flow_blocks
    WHERE id = flow_block_tasks.block_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can update tasks in their flow blocks"
  ON flow_block_tasks FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM flow_blocks
    WHERE id = flow_block_tasks.block_id
    AND user_id = auth.uid()
  ));

CREATE POLICY "Users can delete tasks from their flow blocks"
  ON flow_block_tasks FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM flow_blocks
    WHERE id = flow_block_tasks.block_id
    AND user_id = auth.uid()
  ));

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for day_assistant_tasks
CREATE TRIGGER update_day_assistant_tasks_updated_at
  BEFORE UPDATE ON day_assistant_tasks
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Trigger for user_day_preferences
CREATE TRIGGER update_user_day_preferences_updated_at
  BEFORE UPDATE ON user_day_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
